config/routes.rb
Rails.application.routes.draw do
  root to: "endpoint_configurations#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    resource :targets, only: [:show], :defaults => { :format => :json } do
      member do
        post :hit
      end
    end
  end

  resources :endpoint_configurations
  resources :blacklist, only: [:index]
end

app/models/blacklist.rb
class Blacklist
  include Mongoid::Document

  field :redis_key, type: String
  field :value, type: Hash
  field :status, type: String

  IP_STATUS_ACTIVE = 'ACTIVE'.freeze
  IP_STATUS_BLOCKED = 'BLOCKED'.freeze

  validates :redis_key, :uniqueness => true, :exclusion => { :in => %w(*) }

  def as_json(*a)
    to_hash.as_json(*a)
  end

  def to_hash
    {
      redis_key: redis_key,
      value: value_for_display,
      status: status,
    }
  end

  def value_for_display
    value.select{|k,v| k != "0"}
  end

  def self.newRecord(key, value)
    record = Blacklist.find_by(redis_key: key)
    if record.present?
      record.value = value
    else
      record = Blacklist.new({
        redis_key: key,
        value: value,
        status: value[0],
      })
    end
    record.save!
  end

  def self.update_from_cache
    Blacklist.all.each do |entry|
      value_in_cache = Rails.cache.read(entry.redis_key)
      if value_in_cache.nil? || value_in_cache[0] == IP_STATUS_ACTIVE
        entry.destroy!
      elsif value_in_cache[0] == IP_STATUS_BLOCKED
        entry.value = value_in_cache
        entry.save!
      end
    end 
  end
end

app/models/endpoint_configuration.rb
class EndpointConfiguration
  include Mongoid::Document

  field :request_path, type: String
  field :time_window, type: Integer
  field :max_allowed, type: Integer
  field :track_pathwise, type: Boolean

  validates :request_path, :uniqueness => true
  validate :default_cant_be_pathwise

  def default_cant_be_pathwise
    errors.add(:track_pathwise, "cannot be true for a default request path (*)") if (request_path == "*") && (track_pathwise == true)
  end  

  def as_json(*a)
    to_hash.as_json(*a)
  end

  def to_hash
    {
      request_path: request_path,
      time_window: time_window,
      max_allowed: max_allowed,
    }
  end

  def pathwise_tracking_enabled
    track_pathwise ? "Yes" : "No"
  end

  def sample_key
    track_pathwise ? "#{request_path}-1.2.3.4" : "1.2.3.4"
  end

  def self.default_configuration
    default_conf = EndpointConfiguration.find_by(request_path: "*")
    if default_conf.nil?
      default_conf = EndpointConfiguration.new({
        request_path: "*",
        time_window: 60,
        max_allowed: 100,
        track_pathwise: false
      })
      default_conf.save!
    end
    default_conf
  end
end

app/controllers/api/targets_controller.rb
module Api
  class TargetsController < ApplicationController
    include Tracker

    def show
      render :json => {message: "GET Request registered for IP: #{request.ip}"}, status: :ok
    end

    def hit
      render :json => {message: "POST Request registered for IP: #{request.ip}"}, status: :ok
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/blacklist_controller.rb
class BlacklistController < ApplicationController

  # This controller is merely for convenience
  # This code is not optimised or perfected.
  def index
    Blacklist.update_from_cache
    @list = Blacklist.all
    respond_to do |format|
      format.html
    end
  end
end

app/controllers/concerns/tracker.rb
module Tracker
  extend ActiveSupport::Concern

  included do
    before_action :track_request_ip!
  end

  IP_STATUS_ACTIVE = 'ACTIVE'.freeze
  IP_STATUS_BLOCKED = 'BLOCKED'.freeze

  private

  def track_request_ip!
    allowed, wait_seconds = request_within_limits?
    return if allowed
    render :json => {message: "Rate limit exceeded. Try again in approximately #{wait_seconds} seconds"}, status: :too_many_requests and return
  end

  def request_ip
    # params[:test_ip] || request.ip
    request.ip
  end

  def request_path
    "#{params[:controller]}/#{params[:action]}"
  end

  def get_configuration
    configuration = EndpointConfiguration.find_by(request_path: request_path)
    if configuration.present?
      configuration
    else
      EndpointConfiguration.default_configuration
    end
  end

  def request_within_limits?
    request_timestamp = Time.zone.now
    request_epoch = request_timestamp.change(:sec => 0).to_i
    ip = request_ip
    tracker_config = get_configuration
    key_in_cache = tracker_config.track_pathwise ? "#{request_path}-#{ip}" : ip

    request_data = Rails.cache.read(key_in_cache)
    
    if request_data.nil?
      # if no data exists, this is a fresh request -> serve without checking limits
      Rails.cache.write(key_in_cache, {0 => IP_STATUS_ACTIVE, request_epoch => 1})
      return true, 0
    elsif (request_data.keys.max > request_epoch) && request_data[0].eql?(IP_STATUS_BLOCKED)
      # if already blocked, keep blocking unless manually unblocked
      return false, (request_data.keys.max - request_timestamp.to_i)
    end

    # increment or initialize counter for that minute
    if request_data[request_epoch].present? 
      request_data[request_epoch] += 1 
    else
      request_data[request_epoch] = 1
    end

    # calculate last window average for ip
    window_start = request_epoch - tracker_config.time_window.minutes.to_i
    # purge old data - prevent cluttering of cache
    request_data.reject!{|k,v| k <= window_start}
    # sum of remaining entries is the number of requests made in the last tracking window
    last_window_avg = request_data.values.sum

    

    # decision to block or allow
    if last_window_avg > tracker_config.max_allowed
      # window size in minutes
      actual_window_size = (request_epoch - request_data.keys.min)/60
      dead_wait_period = tracker_config.time_window - actual_window_size
      next_possible_request_time = request_epoch + dead_wait_period.minutes.to_i

      request_data[next_possible_request_time] = 0
      request_data[0] = IP_STATUS_BLOCKED

      Rails.cache.write(key_in_cache, request_data)
      Blacklist.newRecord(key_in_cache, request_data)
      return false, (next_possible_request_time - request_timestamp.to_i)
    else
      request_data[0] = IP_STATUS_ACTIVE
      Rails.cache.write(key_in_cache, request_data)
      return true, 0
    end
  end
end

app/controllers/endpoint_configurations_controller.rb
class EndpointConfigurationsController < ApplicationController
  before_action :set_configuration, only: [:show, :edit, :update, :destroy]

  def index
    @configurations = EndpointConfiguration.all
    respond_to do |format|
      format.html
    end
  end

  def new
    @configuration = EndpointConfiguration.new
  end

  def create
    @configuration = EndpointConfiguration.new(endpoint_configuration_params)
    if @configuration.save!
      respond_to do |format|
        format.html { redirect_to @configuration, notice: 'Endpoint Configuration was successfully created.' }
      end
    end
  rescue => ex
    error_message = @configuration ? @configuration.errors : ex.message
    respond_to do |format|
      format.html { render :new }
    end
  end

  def show
  end

  def edit
  end

  def update
    if @configuration.update!(endpoint_configuration_params)
      respond_to do |format|
        format.html { redirect_to @configuration, notice: 'Endpoint Configuration was successfully updated.' }
      end
    end
  rescue => ex
    error_message = @configuration.errors.present? ? @configuration.errors : ex.message
    respond_to do |format|
      format.html { render :edit }
    end
  end

  def destroy
    @configuration.destroy!
    respond_to do |format|
      format.html { redirect_to endpoint_configurations_path, notice: 'Endpoint Configuration was successfully destroyed.' }
    end
  rescue => ex
    error_message = @configuration.present? ? @configuration.errors : "Endpoint Configuration not found"
    respond_to do |format|
      format.html { render :edit }
    end
  end

  private

  def set_configuration
    @configuration = EndpointConfiguration.find(params[:id])
    rescue ActiveRecord::RecordNotFound => ex
      Rails.logger.warn "Unable to find Endpoint Configuration with request_path: #{params[:id]}"
      # raise ex
  end

  def endpoint_configuration_params
    if params[:endpoint_configuration].blank?
      raise StandardError, "Endpoint Configuration: request_path, time_window and max_allowed are not provided"
    else
      params.require(:endpoint_configuration).permit(:request_path, :time_window, :max_allowed, :track_pathwise)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blacklist/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blacklisted keys in Redis</h1>

<span>
  <p>
    To un-block, to go rails console and type:
    Rails.cache.delete("insert-key-here")
  </p>
</span>
<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @list.each do |entry| %>
      <tr>
        <td><%= entry.redis_key %></td>
        <td><%= entry.value_for_display %></td>
        <td><%= entry.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/endpoint_configurations/_form.html.erb
<%= form_with(model: configuration, local: true) do |form| %>
  <% if configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(configuration.errors.count, "error") %> prohibited this endpoint-configuration from being saved:</h2>

      <ul>
      <% configuration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :request_path %>
    <%= form.text_field :request_path %>
  </div>

  <div class="field">
    <%= form.label :time_window %>
    <%= form.number_field :time_window, step: 1 %>
  </div>

  <div class="field">
    <%= form.label :max_allowed %>
    <%= form.number_field :max_allowed, step: 1 %>
  </div>

  <div class="field">
    <%= form.label :track_pathwise %>
    <%= form.check_box :track_pathwise%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/endpoint_configurations/edit.html.erb
<h1>Editing Endpoint Configuration</h1>

<%= render 'form', configuration: @configuration %>

<%= link_to 'Show', @configuration %> |
<%= link_to 'Back', endpoint_configurations_path %>

app/views/endpoint_configurations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Endpoint Configurations</h1>

<table>
  <thead>
    <tr>
      <th>Request Path</th>
      <th>Time Window</th>
      <th>Max Allowed</th>
      <th>Track Pathwise</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @configurations.each do |configuration| %>
      <tr>
        <td><%= configuration.request_path %></td>
        <td><%= configuration.time_window %> minutes</td>
        <td><%= configuration.max_allowed %> requests</td>
        <td><%= configuration.pathwise_tracking_enabled %></td>
        <td><%= link_to 'Show', configuration %></td>
        <td><%= link_to 'Edit', edit_endpoint_configuration_path(configuration) %></td>
        <td><%= link_to 'Destroy', configuration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New configuration', new_endpoint_configuration_path %>

app/views/endpoint_configurations/new.html.erb
<h1>New Configuration</h1>

<%= render 'form', configuration: @configuration %>

<%= link_to 'Back', endpoint_configurations_path %>

app/views/endpoint_configurations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>IP Address:</strong>
  <%= @configuration.request_path %>
</p>

<p>
  <strong>Time Window:</strong>
  <%= @configuration.time_window %>
</p>

<p>
  <strong>Max Allowed:</strong>
  <%= @configuration.max_allowed %>
</p>

<p>
  <strong>Track Pathwise:</strong>
  <%= @configuration.pathwise_tracking_enabled %>
</p>

<p>
  <strong>Sample Tracking Key (for ip: 1.2.3.4):</strong>
  <%= @configuration.sample_key %>
</p>

<%= link_to 'Edit', edit_endpoint_configuration_path(@configuration) %> |
<%= link_to 'Back', endpoint_configurations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateLimiter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>